//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbladmin
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Kullanýcý Adý Boþ Geçilemez")]
        [StringLength(20,ErrorMessage = "Kullanýcý Adý 20 Karakterden Fazla Olamaz")]
        public string kullanici { get; set; }
        [Required(ErrorMessage = "Þifre Alaný Boþ Geçilemez")]
        [StringLength(20, ErrorMessage = "Þifre 20 Karakterden Fazla Olamaz")]
        public string sifre { get; set; }
    }
}
